"""
prot_test.py file that runs the unittests for prot.py when the file is called or
run using the python CLI.

Group Project for CISC 471, Computational Biology.

By:
    - Andrew Ma (20030440)
    - Rayan Shaikli (20059806)
    - Hershil Devnani (20001045)

There are two ways to run the program, outlined below. Both methods run the
unittests.

Sample Usage:
  $ python -m unittest dna_test.py
  $ python -m main main.py
"""

import unittest
from prot import prot
from parsers import parse_dna_data


class TestProgrammingPartOne(unittest.TestCase):
    """Testing class for the required unittests
    """

    def test_prot_positive_a(self):
        rna_string = parse_dna_data("rosalind_prot_1.txt")
        peptide_string = prot(rna_string)
        solution = "MAMAPRTEINSTRING"

        # make sure solution matches computed result
        self.assertEqual(solution, peptide_string)

    def test_prot_positive_b(self):
        rna_string = parse_dna_data("rosalind_prot_2.txt")
        peptide_string = prot(rna_string)
        solution = \
            "MLSTSVPIVGGTLAATRLLTRTLVNYTCDRRRRRLGVWAYDPIYLINGSAEAKSRSVILSKIGR" \
            "CSYKYYEGAQRPCPTFGARNLWCSHSFTGSECGPWVLLGSLTDSTLKWRRNVCRSPNGVWPSPK" \
            "FRSKWRQRGIAHFSHSAKNCDPTLHQVSPPFRKLQTVNWNTQQPHFAPSVASGDGPFCATCPYC" \
            "EMRSTNILPQSIGIQGSWVLRGLTSYPCLDKSCAYRRALSPKLLSAHNCPHACNGKEQSEPTQD" \
            "KATRLGSRLTGRPGTGNTSFGMTRVQTYSLRQRRVEMNRFCTTESTSVSRKESFHVARRPSPRI" \
            "GLLPTKGCKDHIPALRGCNRNLRFSQARVGRRCVSNPYELRCHGISRDSTVDSFDRRREVGGQP" \
            "RDTGILWMSTFAEGGRSPRDFQKVLGELLYAHIAPADQFIVTNFFCILTNSTRGKSPQSSTGPS" \
            "AVSGGVYGAPMATVGSPRLAPLGDWWEGNVQSNQGSEGIGLRGEQYACYTSLVYRKLIGDRKAL" \
            "SKSCDRTSLATEGCQRNKLLGYLANIVLVISLSKGTPRFEETINIIPNAVSAGGGIISASVKHR" \
            "ADRETTRHVIDLGPLFCLSGGPLKAVKVGSRLNYRNLDMWVRKIKDFWLIESRLRDQTTHTCRL" \
            "CLSLNVIPAFRITSCASVGWHHDANLLCVRGRRGKVKHEAAESLILDRSSEPCSCRHRRKFLEV" \
            "NAVKEKSLGRHWRLLKASNERDDSIYETERTALLQRTVQGIRILKRVFVYLRARSFFTRIDRML" \
            "VRTRIPFSDTRRRNIGPLMGTSVPSASCVPLHCRSGPPLSVLRAIDFSRDQYFDNPTPRDSTTR" \
            "SLFKHIDAENTARDSRRQVLRWMPTLASPPLQALGMDRKLAARRLIGNCESFPIEINGNDAFLP" \
            "GQTQVHRRRIFPMVSSIGEWCAKAGTTCLRRWKRSNRDMAREEVAGRRVAWAETPTGFESQVNR" \
            "FRVQNNPEGVQTYCTLGREALGVRLSRGEVNLLSPGTHRNETCQAIVDEISICSAQLRQPGLKV" \
            "PFIRQTSKTSRCTNYSSTRSQQAVRAKLSSATLTRIASSPLGKGKVRDYLQGTNTLAKTVRREA" \
            "WVLTDPGDPTEFASHSHPRKLSCLIHPYLTPTETSSTEWCRIPRTRRRYLSVILCDVWSLIPSS" \
            "LGRPFVIMKSWWSMREGEAMPTRRCGTMRNFTSRGIVYFKRHKGSSITLQHTFLLVRSIAPANS" \
            "RAICVAHLRSARIRPIRPSLQCRSHIPQADRLAVKQLRSPSPREGLFRCRYTSWNAFVKGLLSL" \
            "LRVTSADVLHSFSNAFEISRANPNNVFFKLSDTLRRGNYSKTHAQDAPFGWAPFYVWAQHSVIW" \
            "GATPTITRRRREYLHSTESANPWTLGKEWVIYAFCNLAATNCPEAALKCYYGYSKILLPGAIDL" \
            "DPLLQCRPRTSYAEVSMRVFTCSRGSFNPEATALRRDTSFRSPTVGIPSRRKALRSEVLLRSAL" \
            "PYPCSWGLATAVLWHNTRFGNDPLFSPLGTIPERTDWAVIQARGDITEFSSGVTLAYGTEVGAC" \
            "QRPSLLANRVDRRIHGKCSSSDIIEYTGCSGKVQGNDVRCLVDVRKGVVEKLIRICYLCTPQCA" \
            "LPRLSRIGQWRIPTPHIISKQYYSLQITRNTSAPTLRQSSITPVGRVTLRDRSQSLLDNDIVGH" \
            "PVEELMQRHSTRGAPLYFRVVHSILFAKRATKDSVPVAGTVRSITLLTNPKSLPTCRPSLSVGG" \
            "CTEDDCRGGVLSERSVILVLPSTRALTSRCRATVRMRCRKFDSNLLYPSSAGEGQQWLCRVQRK" \
            "VVRSSEHLSTWRSVALWSYRGKSHLCSNHSCAYAGIQGHNLGHRHAMSHCEETINSKSMYAPDI" \
            "YVRVDSIYLNGSRFGTACYCTCTLHDCLSFRGHPVTCRKQAQKGVMVKRCLPSDCSGRWYVHRS" \
            "HEKCADAQACAHNALFLTWSRICHHPVTRVNIDASPVGLFDMAHVWLRRGVVPVYRHWTMLYNS" \
            "HSLAQGPSRHLLPITVRNRYATGTSGPIDNCSVGEYMSPPEQSFMPPGRTFIYISSAIQDHRES" \
            "LASSVQKSIGCICAIAPGYRSALGKSSIAGLHHTSALENLRGLFSPLAVAIQLHLTPGLCLLAY" \
            "RRGFHIRSQNIPSPKTLTCRGLVKCIVGQLSGLKQSNLVLRVFTSKKPTNTKIHPLQRTCWHRR" \
            "HRCPAHLGPAVITAGRNRQPIVRLNLLHLGKVYVCSAIAIRCTCRIIQWVKRRVHFKQRLNRHS" \
            "RLRTGSSCPIYGAHHRPVDVEFAYAGELDRSSEGKSCKLRLRTTAYACPHDCVYNLGLLGANYA" \
            "KSRQRSGRTLEAVYSLPDNSLSRRDSLDGGQLGQRHTPVALSRTKITSPPNTTSEMGRPITGPR" \
            "IDIPRAEDSRSTMVHSFNCFDPVRLGEFSALPIFKFGAGPLCACDDFKCRPDIRAGVLGPIPPV" \
            "QLLPASPSPLIRSGSGCPKHSVAERGYCMPTPRCICRVILHSMDNLPAPRGGGHCGSPRISCAG" \
            "RPYSKRGLVFYLRAWLWYYAPLCNRVYLLGAAFRLRLVYSGCPVFSWIPWYVRARTFVSIRTDL" \
            "HFLSSGRCECILVRCGFDSQVWQTSAVSSYAPNLIRASSEGLLDCRQSWLLDSLFHASHARPTA" \
            "AYGRPVVRQNLVKYALGLLRVLAPTGLASIHVRSSTLKEIRVGGRCTMLSSLFYDHSHRGPLHR" \
            "VEIDRVRYRPQIVSFRGFALMGHLTAASAEPKYSTCPTDKRPVSYKQGNGPAVQGCELNGKRER" \
            "ELIDSTGRDNPYPIRTADILFADQVLEAVAVPDCDKVWGTLSWTSDQAAMEFRLTHYGSSRSRW" \
            "WLLLECKCTWGNCLRVRNYTSTGRPCDPLAYFRGRRRPFTPRAAHTQRRGELCEPCISRPAERR" \
            "HQYTRYAIYSLCTDGHGWASGSVGSSHCLSSKSLQISGRLKLSSLGPLVLVKTTEQRAGINTFL" \
            "ERLANRIILGLLVLEMHFTNAASSIVPDVSPNKPRTHITQNIIAPGEKSCWFSKYRLDTVKISG" \
            "LPLRRLTSIGYIPVSPTSAKHIDIVGYLEAPWLSPCLPLEPSNKDTTRHIAISSGAHLRGGSDL" \
            "FTRGISHSSICPPPIYRGSWEVSRNIERLRSLKFLREFAAEILASWGHFGQTDPNFLLVAPLRT" \
            "VYQHDSKKFAKSGERIWEFGSILGLKTAEEGERGWGAQLALRFGDLPGRGKTSKLLLKMSRRMP" \
            "NASKSVSGLIVRHHDYTALRMSLPKTPTRFPVIPKRDCTIGPTIVTLIPLADCMAEEQPMKTLL" \
            "QLFFMPSGNFIWSSQINGPHCAARKLGGHHILNILQSEVTLDLGPLFSKSLPSIKRLCCRLF"

        # make sure solution matches computed result
        self.assertEqual(solution, peptide_string)

    def test_prot_positive_c(self):
        rna_string = parse_dna_data("rosalind_prot_3.txt")
        peptide_string = prot(rna_string)
        solution = \
            "MDRAIMSIIPRLSLNQMCRTGYKLVKISGTEFTGIPLSGPRFNSSRRRATPKINQGNLAFRAAP" \
            "EYRVNLSQFRCTDILQLRLNGPRLDAEITPQTVTPKVVLYSDHPPILSSDKDPFGPRQCQRLVC" \
            "LLLRRENYLARRRGRLASGPPCLYTRTYEAPSHELIGGVNSKTPKKPTIRNYKTHLDFKNATWG" \
            "SAVPVAMMYLHPSKGTVVTSIERAMYLSLFLSKMFILASDRGRVGEILTDIMSPFCAGHMGLGH" \
            "ASHSVIIVRDWRIIEANCLDVDYVSVTLTSTHRELAVVAHQYRALSLSVFTDLRTAKKANKLGP" \
            "AVPSPRRKNVMVASYRVISCALQGGTRVGVKIRGGLYGFLRSRHIRGIECLGLASEVTRNALRR" \
            "RSKLHWQHESSEFSRFPERGSGSSTPRFALTVDRRSSTYERTVPIRRAKWIVCTIASTTGTDPV" \
            "ADALVATQRSDELVGVGPNWAVRARAMTTNHSKLGRILLSHHRVTVLVGPVTRTRARNMSRRLF" \
            "LSTICIPLVVDGCRYYEVGSPRLQVARTLATGSTVCPRPRLCVTAVLCPYELLHRALCCTGERP" \
            "LCRRRKECVQAFLDTHTLFTGEENPIELSRRTLIFANPRIIWPKIYASKFSSNYVSLCNPLRGV" \
            "RLLVVLRLANPASVAGTTGTLALTGVVEVVSDLTEDMALTAHCGAHLLIPAGVTGRLLNGPGQK" \
            "QRFHQRFKMTLSSFIERTSRAAYGGAAPFGPATPHLTALGLLYTIKVKRRSNTTECDSIFATDP" \
            "PLRSRETFINLLRRTQNKFTIGTLVSTISPDPQLVACADRPAFSYASVLLRMGPYALSLIQDHT" \
            "KKNSGLTSYFQHDRELCSVAESERPINKSVGLWACDDVLERPRAYTTCKKMIMEVGHNSCPRHQ" \
            "YRPSAIRCCRGRPAVLSLRNQRPVFHFNQAGALFRCDGQAISLPPFLGGVVARLAVRMIPNYDF" \
            "RPGRKNASRFQDEPVHFVQSLLAKGGINSDYHIPLREALEDTVRRVLSAVYYPMDHHIVDTKRG" \
            "ADLLRCSARFFLRCLGQRCRALYPRQACPAPKQWACPDVECLSVSYGMLFYDPRSHPARSVYFL" \
            "LSSFDQTDYAISTCSARLAVHHPVWSQNNSLVKICDPVKQSEVASGLNWGKDYPSSGFSAIHPT" \
            "RSFCDVAVQSNSNPNRRERPYVAVSKSSKLKSAEIRFKVLGRSTPDSFRRSSQRTFIFIKSEPK" \
            "RSTNRLSSICTEMSSLYDTYNTPKDRVLAPRQACLKLHTADALSNTKHIREHECERRIPTRPES" \
            "RRFEEFKVVDDAVKKVMFLSRPRVETNLALYMELIPATDSCGASKLFIYVRLAPRTITREAAPD" \
            "RAPGINDVSRGEGYLRGVPVKFVTVSHFRFINSRSDSRQLPTIHHGDIYNNPCFNYKVIDRHIG" \
            "CLVTPLLHFAKTVTGHRFKGLPKLIQTCRSRFGSSSHSTDYIYFGPLCQYSKAIRYGSGRITSY" \
            "RLLNAKVAQKDGTSVHSRLLQCRLRPQPTTSTHLSPPQVQQGTLSLSGKRLFLCRNHLANRWDG" \
            "CGMSKCPHAASWHIAPYHGSKVLMRIVILSDLDALGHRYSSLSGQNLSDILHLEEFVTVYATER" \
            "GMEFKIDLPSRGTVVLLQSKYLSRRRACPGLLQAVYLVQLGLSVLMHVRGWIYLGDNFEFELIL" \
            "RTSSITCTRLVVQILAMDPHMTASRNGVRLTPTRNRYARSADTIRPAKHEYYKLRRIISTRPAA" \
            "IARLRLTVVTIAVWCVPPHFQTSTSWADARDILLYRSGAAETLVPKRVKQMALLIGRPYSCPGQ" \
            "VSVTSSKMLISEVLGRREVLPRSFSRRMPFAQSISVKHNKLPHSRQTIHRALCGVMLKVGTVTA" \
            "DSRTPNHRSGYMCCIPCQANPPFICKATGKIFACLLKVVVSLEHVTDMNLTWGLSYTEACPPHM" \
            "AIAVMISFRPGPGRPWMRRTLLLFSSPSSGSIPVRLLDHNRISSLAMRDLSLPWQVWEPVFQCN" \
            "LADAEVTLGYDVVMNKGQVAIKPGVIDRASLSSPHLMIPHPSGFTNKLARPVGNLTNCLRLRTD" \
            "PQSTLGCSIKTPNRSLGRCVLAPRTIRASCELFSAHTITMSDPTSHDRSYLLTRLSTFPPVIRE" \
            "SQQPATVAVLVGINCLLTSRWRGSNQRIPPPKVRYRIRPSEWRCHTPERGTALVTTTDWGLIVT" \
            "EIQLGVTASESVSRGRPPVMMVSESKGLKLECGVDTISKDHCRLVGKHRHKFVCHRTRSVDEVL" \
            "MWCSHLASRNPMLLLLSDWKCHCLEGSIPGRGARFAQGAVKAPPIRKITCLDTAAPQSGRPPKN" \
            "IGLDRAPYQNISRVWTLLHNTMMSPKPLNRKSKALLSCSHRPRISQMRKYVPRWTKLDGRHVKT" \
            "PHNGSPRCSQQKSSLATYVKSNQPLEWPISKQPERADGVIIRENHCSYGLMLLFPRVWPGALIH" \
            "VGYCLLVHLPTYLRDCTPFSRTPLNRFASSSRVPGNDGCAAEDRIRWSMRRYEAVESGKIRPAS" \
            "VFPIEDTGFITRFKQIHIRVPKAQHKLPGVLFYDRDTRSVPRISRMWDILIGKRGCAVQSVFGS" \
            "TSISESFWIDILPRILDDLVKSNIVLQVYGALQRESYISRMEGKGRRIARRSDCHTAVLCQHSA" \
            "LEPVAPNLTPLGDCLSNTCPRSAGVGDTYGAKRKAVAFWPGHALRRLIAGNVRLYTLGNRCSHL" \
            "PFFLTKSGFPFYGAHGTLAKSYSIGKPPGASPLVHFLLTFVALEFLEGIKCPSRQCVKDLNHIV" \
            "KNLFPQARVPKRVGPRRSNLLLRIPKGHILFSYGVRSSLIPCNGNSAGTPVSSLIEVLPRLLLQ" \
            "QSVLKHPMPRPPQRSLRHPFSATRRHFGPLGAGPVLKRHPFSAGRFRFSASRIRGHRLYSMRTK" \
            "GKVIKCHSLNMLQTLAPQNITPQRVAGLAQPSQQHVHRSSLGCSQIWQSRELWFEFGSVAKRVL" \
            "TNFGVPGVGLFLTTMSESP"

        # make sure solution matches computed result
        self.assertEqual(solution, peptide_string)

    def test_prot_negative(self):
        rna_string = parse_dna_data("rosalind_prot_4.txt")
        peptide_string = prot(rna_string)
        solution = None

        # make sure solution matches computed result
        self.assertEqual(solution, peptide_string)


if __name__ == '__main__':
    unittest.main()
